// Generated by scripts/generate-tiers.ts from Pokemon Showdown formats data.
export type TierInfo = { tier?: string; doublesTier?: string; natDexTier?: string }
export const TIER_DATA: Record<string, TierInfo> = {
  "bulbasaur": {
    "tier": "LC"
  },
  "ivysaur": {
    "tier": "NFE"
  },
  "venusaur": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "venusaurmega": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "venusaurgmax": {
    "tier": "Illegal"
  },
  "charmander": {
    "tier": "LC"
  },
  "charmeleon": {
    "tier": "NFE"
  },
  "charizard": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "charizardmegax": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "charizardmegay": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "charizardgmax": {
    "tier": "Illegal"
  },
  "squirtle": {
    "tier": "LC"
  },
  "wartortle": {
    "tier": "NFE"
  },
  "blastoise": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "blastoisemega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "blastoisegmax": {
    "tier": "Illegal"
  },
  "caterpie": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "metapod": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "butterfree": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "butterfreegmax": {
    "tier": "Illegal"
  },
  "weedle": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "kakuna": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "beedrill": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "beedrillmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pidgey": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "pidgeotto": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "pidgeot": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pidgeotmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "rattata": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "rattataalola": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "raticate": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "raticatealola": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "raticatealolatotem": {
    "tier": "Illegal"
  },
  "spearow": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "fearow": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "ekans": {
    "tier": "LC"
  },
  "arbok": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pichu": {
    "tier": "LC"
  },
  "pichuspikyeared": {
    "tier": "Illegal"
  },
  "pikachu": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachucosplay": {
    "tier": "Illegal"
  },
  "pikachurockstar": {
    "tier": "Illegal"
  },
  "pikachubelle": {
    "tier": "Illegal"
  },
  "pikachupopstar": {
    "tier": "Illegal"
  },
  "pikachuphd": {
    "tier": "Illegal"
  },
  "pikachulibre": {
    "tier": "Illegal"
  },
  "pikachuoriginal": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachuhoenn": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachusinnoh": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachuunova": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachukalos": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachualola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachupartner": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pikachustarter": {
    "tier": "Illegal"
  },
  "pikachugmax": {
    "tier": "Illegal"
  },
  "pikachuworld": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "raichu": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "raichualola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "raichumegax": {
    "tier": "Illegal"
  },
  "raichumegay": {
    "tier": "Illegal"
  },
  "sandshrew": {
    "tier": "LC"
  },
  "sandshrewalola": {
    "tier": "LC"
  },
  "sandslash": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sandslashalola": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "nidoranf": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "nidorina": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "nidoqueen": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "nidoranm": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "nidorino": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "nidoking": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "cleffa": {
    "tier": "LC"
  },
  "clefairy": {
    "tier": "NFE",
    "doublesTier": "DUU",
    "natDexTier": "NFE"
  },
  "clefable": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "clefablemega": {
    "tier": "Illegal"
  },
  "vulpix": {
    "tier": "NFE",
    "doublesTier": "NFE",
    "natDexTier": "LC"
  },
  "vulpixalola": {
    "tier": "NFE"
  },
  "ninetales": {
    "tier": "ZU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "ninetalesalola": {
    "tier": "PU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "igglybuff": {
    "tier": "LC"
  },
  "jigglypuff": {
    "tier": "NFE"
  },
  "wigglytuff": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "zubat": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "golbat": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "crobat": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "oddish": {
    "tier": "LC"
  },
  "gloom": {
    "tier": "NFE"
  },
  "vileplume": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "bellossom": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "paras": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "parasect": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "venonat": {
    "tier": "LC"
  },
  "venomoth": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "diglett": {
    "tier": "NFE"
  },
  "diglettalola": {
    "tier": "LC"
  },
  "dugtrio": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dugtrioalola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "meowth": {
    "tier": "LC"
  },
  "meowthalola": {
    "tier": "LC"
  },
  "meowthgalar": {
    "tier": "LC"
  },
  "meowthgmax": {
    "tier": "Illegal"
  },
  "persian": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "persianalola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "perrserker": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "psyduck": {
    "tier": "LC"
  },
  "golduck": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "mankey": {
    "tier": "LC"
  },
  "primeape": {
    "tier": "NFE",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "growlithe": {
    "tier": "LC"
  },
  "growlithehisui": {
    "tier": "LC"
  },
  "arcanine": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "arcaninehisui": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "poliwag": {
    "tier": "LC"
  },
  "poliwhirl": {
    "tier": "NFE"
  },
  "poliwrath": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "politoed": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "abra": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "kadabra": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "alakazam": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "alakazammega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "machop": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "machoke": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "machamp": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "machampgmax": {
    "tier": "Illegal"
  },
  "bellsprout": {
    "tier": "LC"
  },
  "weepinbell": {
    "tier": "NFE"
  },
  "victreebel": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "victreebelmega": {
    "tier": "Illegal"
  },
  "tentacool": {
    "tier": "LC"
  },
  "tentacruel": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "geodude": {
    "tier": "LC"
  },
  "geodudealola": {
    "tier": "LC"
  },
  "graveler": {
    "tier": "NFE"
  },
  "graveleralola": {
    "tier": "NFE"
  },
  "golem": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "golemalola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ponyta": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "ponytagalar": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "rapidash": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "rapidashgalar": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "slowpoke": {
    "tier": "LC"
  },
  "slowpokegalar": {
    "tier": "LC"
  },
  "slowbro": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "slowbromega": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "slowbrogalar": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "slowking": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "slowkinggalar": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "magnemite": {
    "tier": "LC"
  },
  "magneton": {
    "tier": "ZU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "magnezone": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "farfetchd": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "farfetchdgalar": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "sirfetchd": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "doduo": {
    "tier": "LC"
  },
  "dodrio": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "seel": {
    "tier": "LC"
  },
  "dewgong": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "grimer": {
    "tier": "LC"
  },
  "grimeralola": {
    "tier": "LC"
  },
  "muk": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "mukalola": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shellder": {
    "tier": "NFE"
  },
  "cloyster": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gastly": {
    "tier": "NFE"
  },
  "haunter": {
    "tier": "NFE"
  },
  "gengar": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "gengarmega": {
    "tier": "Illegal",
    "natDexTier": "AG"
  },
  "gengargmax": {
    "tier": "Illegal"
  },
  "onix": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "steelix": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "steelixmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "drowzee": {
    "tier": "LC"
  },
  "hypno": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "krabby": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "kingler": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kinglergmax": {
    "tier": "Illegal"
  },
  "voltorb": {
    "tier": "LC"
  },
  "voltorbhisui": {
    "tier": "NFE",
    "doublesTier": "LC",
    "natDexTier": "LC"
  },
  "electrode": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "electrodehisui": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "exeggcute": {
    "tier": "LC"
  },
  "exeggutor": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "exeggutoralola": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cubone": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "marowak": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "marowakalola": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "marowakalolatotem": {
    "tier": "Illegal"
  },
  "tyrogue": {
    "tier": "LC"
  },
  "hitmonlee": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hitmonchan": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hitmontop": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lickitung": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "lickilicky": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "koffing": {
    "tier": "LC"
  },
  "weezing": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "weezinggalar": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rhyhorn": {
    "tier": "LC"
  },
  "rhydon": {
    "tier": "PU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "rhyperior": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "happiny": {
    "tier": "LC"
  },
  "chansey": {
    "tier": "NU",
    "doublesTier": "NFE",
    "natDexTier": "UU"
  },
  "blissey": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "tangela": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "tangrowth": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kangaskhan": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kangaskhanmega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "horsea": {
    "tier": "LC"
  },
  "seadra": {
    "tier": "NFE"
  },
  "kingdra": {
    "tier": "ZUBL",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "goldeen": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "seaking": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "staryu": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "starmie": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "starmiemega": {
    "tier": "Illegal"
  },
  "mimejr": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "mrmime": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mrmimegalar": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "mrrime": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "scyther": {
    "tier": "NU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "scizor": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "scizormega": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "kleavor": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "smoochum": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "jynx": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "elekid": {
    "tier": "LC"
  },
  "electabuzz": {
    "tier": "NFE"
  },
  "electivire": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "magby": {
    "tier": "NFE"
  },
  "magmar": {
    "tier": "NFE"
  },
  "magmortar": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pinsir": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pinsirmega": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "tauros": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "taurospaldeacombat": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "taurospaldeablaze": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "taurospaldeaaqua": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "magikarp": {
    "tier": "LC"
  },
  "gyarados": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "gyaradosmega": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "lapras": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "laprasgmax": {
    "tier": "Illegal"
  },
  "ditto": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "eevee": {
    "tier": "LC"
  },
  "eeveestarter": {
    "tier": "Illegal"
  },
  "eeveegmax": {
    "tier": "Illegal"
  },
  "vaporeon": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "jolteon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "flareon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "espeon": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "umbreon": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "leafeon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "glaceon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sylveon": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "porygon": {
    "tier": "NFE"
  },
  "porygon2": {
    "tier": "PU",
    "doublesTier": "DUU",
    "natDexTier": "NFE"
  },
  "porygonz": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "omanyte": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "omastar": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kabuto": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "kabutops": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "aerodactyl": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "aerodactylmega": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "munchlax": {
    "tier": "LC"
  },
  "snorlax": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "snorlaxgmax": {
    "tier": "Illegal"
  },
  "articuno": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "articunogalar": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "zapdos": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "zapdosgalar": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "moltres": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "moltresgalar": {
    "tier": "UUBL",
    "doublesTier": "DOU",
    "natDexTier": "RUBL"
  },
  "dratini": {
    "tier": "LC"
  },
  "dragonair": {
    "tier": "NFE"
  },
  "dragonite": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "dragonitemega": {
    "tier": "Illegal"
  },
  "mewtwo": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "mewtwomegax": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "mewtwomegay": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "mew": {
    "tier": "UU",
    "doublesTier": "DUU",
    "natDexTier": "UU"
  },
  "chikorita": {
    "tier": "LC"
  },
  "bayleef": {
    "tier": "NFE"
  },
  "meganium": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "meganiummega": {
    "tier": "Illegal"
  },
  "cyndaquil": {
    "tier": "LC"
  },
  "quilava": {
    "tier": "NFE"
  },
  "typhlosion": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "typhlosionhisui": {
    "tier": "PU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "totodile": {
    "tier": "LC"
  },
  "croconaw": {
    "tier": "NFE"
  },
  "feraligatr": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "feraligatrmega": {
    "tier": "Illegal"
  },
  "sentret": {
    "tier": "LC"
  },
  "furret": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hoothoot": {
    "tier": "LC"
  },
  "noctowl": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ledyba": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "ledian": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "spinarak": {
    "tier": "LC"
  },
  "ariados": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chinchou": {
    "tier": "LC"
  },
  "lanturn": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "togepi": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "togetic": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "togekiss": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "natu": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "xatu": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mareep": {
    "tier": "LC"
  },
  "flaaffy": {
    "tier": "NFE"
  },
  "ampharos": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ampharosmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "azurill": {
    "tier": "LC"
  },
  "marill": {
    "tier": "NFE"
  },
  "azumarill": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "bonsly": {
    "tier": "LC"
  },
  "sudowoodo": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hoppip": {
    "tier": "LC"
  },
  "skiploom": {
    "tier": "NFE"
  },
  "jumpluff": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "aipom": {
    "tier": "NFE"
  },
  "ambipom": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sunkern": {
    "tier": "LC"
  },
  "sunflora": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "yanma": {
    "tier": "NFE"
  },
  "yanmega": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "wooper": {
    "tier": "LC"
  },
  "wooperpaldea": {
    "tier": "LC"
  },
  "quagsire": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "murkrow": {
    "tier": "NFE",
    "doublesTier": "DUU"
  },
  "honchkrow": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "misdreavus": {
    "tier": "NFE"
  },
  "mismagius": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "unown": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wynaut": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "wobbuffet": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "girafarig": {
    "tier": "NFE"
  },
  "farigiraf": {
    "tier": "ZU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "pineco": {
    "tier": "LC"
  },
  "forretress": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dunsparce": {
    "tier": "NFE"
  },
  "dudunsparce": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gligar": {
    "tier": "NU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "gliscor": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "snubbull": {
    "tier": "LC"
  },
  "granbull": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "qwilfish": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "qwilfishhisui": {
    "tier": "PU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "overqwil": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shuckle": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "heracross": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "heracrossmega": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "sneasel": {
    "tier": "ZU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "sneaselhisui": {
    "tier": "ZU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "weavile": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "sneasler": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "teddiursa": {
    "tier": "LC"
  },
  "ursaring": {
    "tier": "NFE"
  },
  "ursaluna": {
    "tier": "UUBL",
    "doublesTier": "DOU",
    "natDexTier": "RUBL"
  },
  "ursalunabloodmoon": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "slugma": {
    "tier": "LC"
  },
  "magcargo": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "swinub": {
    "tier": "LC"
  },
  "piloswine": {
    "tier": "NFE"
  },
  "mamoswine": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "corsola": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "corsolagalar": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "cursola": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "remoraid": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "octillery": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "delibird": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "mantyke": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "mantine": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "skarmory": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "skarmorymega": {
    "tier": "Illegal"
  },
  "houndour": {
    "tier": "LC"
  },
  "houndoom": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "houndoommega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "phanpy": {
    "tier": "LC"
  },
  "donphan": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "stantler": {
    "tier": "NFE"
  },
  "wyrdeer": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "smeargle": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "miltank": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "raikou": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "entei": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "suicune": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "larvitar": {
    "tier": "LC"
  },
  "pupitar": {
    "tier": "NFE"
  },
  "tyranitar": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "UU"
  },
  "tyranitarmega": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "lugia": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "hooh": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "celebi": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "treecko": {
    "tier": "LC"
  },
  "grovyle": {
    "tier": "NFE"
  },
  "sceptile": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sceptilemega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "torchic": {
    "tier": "NFE"
  },
  "combusken": {
    "tier": "NFE"
  },
  "blaziken": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "blazikenmega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "mudkip": {
    "tier": "LC"
  },
  "marshtomp": {
    "tier": "NFE"
  },
  "swampert": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "swampertmega": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "poochyena": {
    "tier": "LC"
  },
  "mightyena": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "zigzagoon": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "zigzagoongalar": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "linoone": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "linoonegalar": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "obstagoon": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wurmple": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "silcoon": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "beautifly": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "cascoon": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "dustox": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "lotad": {
    "tier": "LC"
  },
  "lombre": {
    "tier": "NFE"
  },
  "ludicolo": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "seedot": {
    "tier": "LC"
  },
  "nuzleaf": {
    "tier": "NFE"
  },
  "shiftry": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "taillow": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "swellow": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wingull": {
    "tier": "LC"
  },
  "pelipper": {
    "tier": "UUBL",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "ralts": {
    "tier": "LC"
  },
  "kirlia": {
    "tier": "NFE"
  },
  "gardevoir": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gardevoirmega": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "gallade": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "gallademega": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "surskit": {
    "tier": "LC"
  },
  "masquerain": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shroomish": {
    "tier": "LC"
  },
  "breloom": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "slakoth": {
    "tier": "LC"
  },
  "vigoroth": {
    "tier": "NFE"
  },
  "slaking": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "nincada": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "ninjask": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "shedinja": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "whismur": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "loudred": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "exploud": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "makuhita": {
    "tier": "LC"
  },
  "hariyama": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "nosepass": {
    "tier": "LC"
  },
  "probopass": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "skitty": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "delcatty": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "sableye": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sableyemega": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "mawile": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mawilemega": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "aron": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "lairon": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "aggron": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "aggronmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "meditite": {
    "tier": "NFE"
  },
  "medicham": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "medichammega": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "electrike": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "manectric": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "manectricmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "plusle": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "minun": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "volbeat": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "illumise": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "budew": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "roselia": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "roserade": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "gulpin": {
    "tier": "LC"
  },
  "swalot": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "carvanha": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "sharpedo": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "sharpedomega": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "wailmer": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "wailord": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "numel": {
    "tier": "LC"
  },
  "camerupt": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cameruptmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "torkoal": {
    "tier": "ZU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "spoink": {
    "tier": "LC"
  },
  "grumpig": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "spinda": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "trapinch": {
    "tier": "LC"
  },
  "vibrava": {
    "tier": "NFE"
  },
  "flygon": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cacnea": {
    "tier": "LC"
  },
  "cacturne": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "swablu": {
    "tier": "LC"
  },
  "altaria": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "altariamega": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "zangoose": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "seviper": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lunatone": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "solrock": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "barboach": {
    "tier": "LC"
  },
  "whiscash": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "corphish": {
    "tier": "LC"
  },
  "crawdaunt": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "baltoy": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "claydol": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "lileep": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "cradily": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "anorith": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "armaldo": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "feebas": {
    "tier": "LC"
  },
  "milotic": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "castform": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kecleon": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "shuppet": {
    "tier": "LC"
  },
  "banette": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "banettemega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "duskull": {
    "tier": "LC"
  },
  "dusclops": {
    "tier": "NFE"
  },
  "dusknoir": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "tropius": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chingling": {
    "tier": "LC"
  },
  "chimecho": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chimechomega": {
    "tier": "Illegal"
  },
  "absol": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "absolmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "absolmegaz": {
    "tier": "Illegal"
  },
  "snorunt": {
    "tier": "LC"
  },
  "glalie": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "glaliemega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "froslass": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "froslassmega": {
    "tier": "Illegal"
  },
  "spheal": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "sealeo": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "walrein": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "clamperl": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "huntail": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "gorebyss": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "relicanth": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "luvdisc": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "bagon": {
    "tier": "LC"
  },
  "shelgon": {
    "tier": "NFE"
  },
  "salamence": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "salamencemega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "beldum": {
    "tier": "LC"
  },
  "metang": {
    "tier": "NFE"
  },
  "metagross": {
    "tier": "UU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "metagrossmega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "regirock": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "regice": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "registeel": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "latias": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "latiasmega": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "latios": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "latiosmega": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "kyogre": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "kyogreprimal": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "groudon": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "groudonprimal": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "rayquaza": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "rayquazamega": {
    "tier": "Illegal",
    "natDexTier": "AG"
  },
  "jirachi": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "deoxys": {
    "tier": "Uber",
    "doublesTier": "(DUU)",
    "natDexTier": "Uber"
  },
  "deoxysattack": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "deoxysdefense": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "deoxysspeed": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "Uber"
  },
  "turtwig": {
    "tier": "LC"
  },
  "grotle": {
    "tier": "NFE"
  },
  "torterra": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chimchar": {
    "tier": "LC"
  },
  "monferno": {
    "tier": "NFE"
  },
  "infernape": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "piplup": {
    "tier": "LC"
  },
  "prinplup": {
    "tier": "NFE"
  },
  "empoleon": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "starly": {
    "tier": "LC"
  },
  "staravia": {
    "tier": "NFE"
  },
  "staraptor": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "staraptormega": {
    "tier": "Illegal"
  },
  "bidoof": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "bibarel": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "kricketot": {
    "tier": "LC"
  },
  "kricketune": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shinx": {
    "tier": "LC"
  },
  "luxio": {
    "tier": "NFE"
  },
  "luxray": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cranidos": {
    "tier": "LC"
  },
  "rampardos": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shieldon": {
    "tier": "LC"
  },
  "bastiodon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "burmy": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "wormadam": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wormadamsandy": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wormadamtrash": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mothim": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "combee": {
    "tier": "LC"
  },
  "vespiquen": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pachirisu": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "buizel": {
    "tier": "LC"
  },
  "floatzel": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cherubi": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "cherrim": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "shellos": {
    "tier": "LC"
  },
  "gastrodon": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "drifloon": {
    "tier": "LC",
    "natDexTier": "NFE"
  },
  "drifblim": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "buneary": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "lopunny": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "lopunnymega": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "glameow": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "purugly": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "stunky": {
    "tier": "LC"
  },
  "skuntank": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "bronzor": {
    "tier": "LC"
  },
  "bronzong": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chatot": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "spiritomb": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gible": {
    "tier": "LC"
  },
  "gabite": {
    "tier": "NFE"
  },
  "garchomp": {
    "tier": "UUBL",
    "doublesTier": "DUU",
    "natDexTier": "OU"
  },
  "garchompmega": {
    "tier": "Illegal",
    "natDexTier": "(OU)"
  },
  "garchompmegaz": {
    "tier": "Illegal"
  },
  "riolu": {
    "tier": "LC"
  },
  "lucario": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lucariomega": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "lucariomegaz": {
    "tier": "Illegal"
  },
  "hippopotas": {
    "tier": "LC"
  },
  "hippowdon": {
    "tier": "UU",
    "doublesTier": "DUU",
    "natDexTier": "UU"
  },
  "skorupi": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "drapion": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "croagunk": {
    "tier": "LC"
  },
  "toxicroak": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "carnivine": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "finneon": {
    "tier": "LC"
  },
  "lumineon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "snover": {
    "tier": "LC"
  },
  "abomasnow": {
    "tier": "ZU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "abomasnowmega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "rotom": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rotomheat": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rotomwash": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "rotomfrost": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rotomfan": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rotommow": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "uxie": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "mesprit": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "azelf": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dialga": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "dialgaorigin": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "palkia": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "palkiaorigin": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "heatran": {
    "tier": "OU",
    "doublesTier": "DUU",
    "natDexTier": "OU"
  },
  "heatranmega": {
    "tier": "Illegal"
  },
  "regigigas": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "giratina": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "giratinaorigin": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "cresselia": {
    "tier": "NUBL",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "phione": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "manaphy": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "darkrai": {
    "tier": "OU",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "darkraimega": {
    "tier": "Illegal"
  },
  "shaymin": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shayminsky": {
    "tier": "Uber",
    "doublesTier": "(DUU)",
    "natDexTier": "Uber"
  },
  "arceus": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "victini": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "snivy": {
    "tier": "NFE"
  },
  "servine": {
    "tier": "NFE"
  },
  "serperior": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "tepig": {
    "tier": "LC"
  },
  "pignite": {
    "tier": "NFE"
  },
  "emboar": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "emboarmega": {
    "tier": "Illegal"
  },
  "oshawott": {
    "tier": "LC"
  },
  "dewott": {
    "tier": "NFE"
  },
  "samurott": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "samurotthisui": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "patrat": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "watchog": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "lillipup": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "herdier": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "stoutland": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "purrloin": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "liepard": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pansage": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "simisage": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pansear": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "simisear": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "panpour": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "simipour": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "munna": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "musharna": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "pidove": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "tranquill": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "unfezant": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "blitzle": {
    "tier": "LC"
  },
  "zebstrika": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "roggenrola": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "boldore": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "gigalith": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "woobat": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "swoobat": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "drilbur": {
    "tier": "LC"
  },
  "excadrill": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "excadrillmega": {
    "tier": "Illegal"
  },
  "audino": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "audinomega": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "timburr": {
    "tier": "LC"
  },
  "gurdurr": {
    "tier": "ZU",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "conkeldurr": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "tympole": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "palpitoad": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "seismitoad": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "throh": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "sawk": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "sewaddle": {
    "tier": "LC"
  },
  "swadloon": {
    "tier": "NFE"
  },
  "leavanny": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "venipede": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "whirlipede": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "scolipede": {
    "tier": "Illegal",
    "natDexTier": "RUBL"
  },
  "scolipedemega": {
    "tier": "Illegal"
  },
  "cottonee": {
    "tier": "LC"
  },
  "whimsicott": {
    "tier": "ZU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "petilil": {
    "tier": "LC"
  },
  "lilligant": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lilliganthisui": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "basculin": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "basculegion": {
    "tier": "NU",
    "doublesTier": "DUber",
    "natDexTier": "RU"
  },
  "basculegionf": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "sandile": {
    "tier": "LC"
  },
  "krokorok": {
    "tier": "NFE"
  },
  "krookodile": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "darumaka": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "darumakagalar": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "darmanitan": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "darmanitangalar": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "maractus": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "dwebble": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "crustle": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "scraggy": {
    "tier": "NFE"
  },
  "scrafty": {
    "tier": "PU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "scraftymega": {
    "tier": "Illegal"
  },
  "sigilyph": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "yamask": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "yamaskgalar": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "cofagrigus": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "runerigus": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "tirtouga": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "carracosta": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "archen": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "archeops": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "trubbish": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "garbodor": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "garbodorgmax": {
    "tier": "Illegal"
  },
  "zorua": {
    "tier": "LC"
  },
  "zoruahisui": {
    "tier": "LC"
  },
  "zoroark": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "zoroarkhisui": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "minccino": {
    "tier": "LC"
  },
  "cinccino": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gothita": {
    "tier": "LC"
  },
  "gothorita": {
    "tier": "NFE"
  },
  "gothitelle": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "solosis": {
    "tier": "LC"
  },
  "duosion": {
    "tier": "NFE"
  },
  "reuniclus": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ducklett": {
    "tier": "LC"
  },
  "swanna": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "vanillite": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "vanillish": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "vanilluxe": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "deerling": {
    "tier": "LC"
  },
  "sawsbuck": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "emolga": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "karrablast": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "escavalier": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "foongus": {
    "tier": "LC"
  },
  "amoonguss": {
    "tier": "PU",
    "doublesTier": "DOU",
    "natDexTier": "UU"
  },
  "frillish": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "jellicent": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "alomomola": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "joltik": {
    "tier": "LC"
  },
  "galvantula": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ferroseed": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "ferrothorn": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "klink": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "klang": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "klinklang": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "tynamo": {
    "tier": "LC"
  },
  "eelektrik": {
    "tier": "NFE"
  },
  "eelektross": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "eelektrossmega": {
    "tier": "Illegal"
  },
  "elgyem": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "beheeyem": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "litwick": {
    "tier": "LC"
  },
  "lampent": {
    "tier": "NFE"
  },
  "chandelure": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chandeluremega": {
    "tier": "Illegal"
  },
  "axew": {
    "tier": "LC"
  },
  "fraxure": {
    "tier": "NFE"
  },
  "haxorus": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "cubchoo": {
    "tier": "LC"
  },
  "beartic": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cryogonal": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "shelmet": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "accelgor": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "stunfisk": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "stunfiskgalar": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mienfoo": {
    "tier": "LC"
  },
  "mienshao": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "druddigon": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "golett": {
    "tier": "LC"
  },
  "golurk": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "golurkmega": {
    "tier": "Illegal"
  },
  "pawniard": {
    "tier": "LC"
  },
  "bisharp": {
    "tier": "RU",
    "doublesTier": "NFE",
    "natDexTier": "UU"
  },
  "bouffalant": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "rufflet": {
    "tier": "NFE"
  },
  "braviary": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "braviaryhisui": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "vullaby": {
    "tier": "LC"
  },
  "mandibuzz": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "heatmor": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "durant": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "deino": {
    "tier": "LC"
  },
  "zweilous": {
    "tier": "NFE"
  },
  "hydreigon": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "larvesta": {
    "tier": "LC"
  },
  "volcarona": {
    "tier": "Uber",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "cobalion": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "terrakion": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "virizion": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "tornadus": {
    "tier": "NU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "tornadustherian": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "thundurus": {
    "tier": "RUBL",
    "doublesTier": "DUU",
    "natDexTier": "UU"
  },
  "thundurustherian": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "reshiram": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "zekrom": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "landorus": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "landorustherian": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "kyurem": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "kyuremblack": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "kyuremwhite": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "keldeo": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "meloetta": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "genesect": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "genesectburn": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "genesectchill": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "genesectdouse": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "genesectshock": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "chespin": {
    "tier": "LC"
  },
  "quilladin": {
    "tier": "NFE"
  },
  "chesnaught": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chesnaughtmega": {
    "tier": "Illegal"
  },
  "fennekin": {
    "tier": "LC"
  },
  "braixen": {
    "tier": "NFE"
  },
  "delphox": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "delphoxmega": {
    "tier": "Illegal"
  },
  "froakie": {
    "tier": "LC"
  },
  "frogadier": {
    "tier": "NFE"
  },
  "greninja": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "greninjaash": {
    "tier": "Illegal"
  },
  "greninjamega": {
    "tier": "Illegal"
  },
  "bunnelby": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "diggersby": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "fletchling": {
    "tier": "LC"
  },
  "fletchinder": {
    "tier": "NFE"
  },
  "talonflame": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "scatterbug": {
    "tier": "LC"
  },
  "spewpa": {
    "tier": "NFE"
  },
  "vivillon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "litleo": {
    "tier": "LC"
  },
  "pyroar": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pyroarmega": {
    "tier": "Illegal"
  },
  "flabebe": {
    "tier": "LC"
  },
  "floette": {
    "tier": "NFE"
  },
  "floetteeternal": {
    "tier": "Illegal"
  },
  "floettemega": {
    "tier": "Illegal"
  },
  "florges": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "skiddo": {
    "tier": "LC"
  },
  "gogoat": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pancham": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "pangoro": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "furfrou": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "espurr": {
    "tier": "LC"
  },
  "meowstic": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "meowsticmmega": {
    "tier": "Illegal"
  },
  "meowsticfmega": {
    "tier": "Illegal"
  },
  "honedge": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "doublade": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "aegislash": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "spritzee": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "aromatisse": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "swirlix": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "slurpuff": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "inkay": {
    "tier": "LC"
  },
  "malamar": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "malamarmega": {
    "tier": "Illegal"
  },
  "binacle": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "barbaracle": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "barbaraclemega": {
    "tier": "Illegal"
  },
  "skrelp": {
    "tier": "LC"
  },
  "dragalge": {
    "tier": "PUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dragalgemega": {
    "tier": "Illegal"
  },
  "clauncher": {
    "tier": "LC"
  },
  "clawitzer": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "helioptile": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "heliolisk": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "tyrunt": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "tyrantrum": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "amaura": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "aurorus": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "hawlucha": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "hawluchamega": {
    "tier": "Illegal"
  },
  "dedenne": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "carbink": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "goomy": {
    "tier": "LC"
  },
  "sliggoo": {
    "tier": "NFE"
  },
  "sliggoohisui": {
    "tier": "NFE"
  },
  "goodra": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "goodrahisui": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "klefki": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "phantump": {
    "tier": "LC"
  },
  "trevenant": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pumpkaboo": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "gourgeist": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "bergmite": {
    "tier": "LC"
  },
  "avalugg": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "avalugghisui": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "noibat": {
    "tier": "LC"
  },
  "noivern": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "xerneas": {
    "tier": "Illegal",
    "natDexTier": "AG"
  },
  "xerneasneutral": {
    "tier": "Illegal"
  },
  "yveltal": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "zygarde": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "zygarde10": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "zygardecomplete": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "zygardemega": {
    "tier": "Illegal"
  },
  "diancie": {
    "tier": "RU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "dianciemega": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "hoopa": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hoopaunbound": {
    "tier": "UUBL",
    "doublesTier": "DUU",
    "natDexTier": "UUBL"
  },
  "volcanion": {
    "tier": "RUBL",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "rowlet": {
    "tier": "LC"
  },
  "dartrix": {
    "tier": "NFE"
  },
  "decidueye": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "decidueyehisui": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "litten": {
    "tier": "LC"
  },
  "torracat": {
    "tier": "NFE"
  },
  "incineroar": {
    "tier": "NU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "popplio": {
    "tier": "LC"
  },
  "brionne": {
    "tier": "NFE"
  },
  "primarina": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "pikipek": {
    "tier": "LC"
  },
  "trumbeak": {
    "tier": "NFE"
  },
  "toucannon": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "yungoos": {
    "tier": "LC"
  },
  "gumshoos": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gumshoostotem": {
    "tier": "Illegal"
  },
  "grubbin": {
    "tier": "LC"
  },
  "charjabug": {
    "tier": "NFE"
  },
  "vikavolt": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "vikavolttotem": {
    "tier": "Illegal"
  },
  "crabrawler": {
    "tier": "LC"
  },
  "crabominable": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "crabominablemega": {
    "tier": "Illegal"
  },
  "oricorio": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "oricoriopompom": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "oricoriopau": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "oricoriosensu": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cutiefly": {
    "tier": "NFE"
  },
  "ribombee": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ribombeetotem": {
    "tier": "Illegal"
  },
  "rockruff": {
    "tier": "LC"
  },
  "rockruffdusk": {
    "tier": "LC"
  },
  "lycanroc": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lycanrocmidnight": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lycanrocdusk": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "wishiwashi": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "mareanie": {
    "tier": "LC"
  },
  "toxapex": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "mudbray": {
    "tier": "LC"
  },
  "mudsdale": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dewpider": {
    "tier": "LC"
  },
  "araquanid": {
    "tier": "NU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "araquanidtotem": {
    "tier": "Illegal"
  },
  "fomantis": {
    "tier": "LC"
  },
  "lurantis": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "lurantistotem": {
    "tier": "Illegal"
  },
  "morelull": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "shiinotic": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "salandit": {
    "tier": "LC"
  },
  "salazzle": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "salazzletotem": {
    "tier": "Illegal"
  },
  "stufful": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "bewear": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "bounsweet": {
    "tier": "LC"
  },
  "steenee": {
    "tier": "NFE"
  },
  "tsareena": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "comfey": {
    "tier": "RUBL",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "oranguru": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "passimian": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "wimpod": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "golisopod": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "golisopodmega": {
    "tier": "Illegal"
  },
  "sandygast": {
    "tier": "LC"
  },
  "palossand": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pyukumuku": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "typenull": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "silvally": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallybug": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallydark": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallydragon": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyelectric": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyfairy": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyfighting": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyfire": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyflying": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyghost": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallygrass": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyground": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyice": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallypoison": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallypsychic": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallyrock": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallysteel": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "silvallywater": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "minior": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "komala": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "turtonator": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "togedemaru": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "togedemarutotem": {
    "tier": "Illegal"
  },
  "mimikyu": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "mimikyutotem": {
    "tier": "Illegal"
  },
  "mimikyubustedtotem": {
    "tier": "Illegal"
  },
  "bruxish": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "drampa": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "drampamega": {
    "tier": "Illegal"
  },
  "dhelmise": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "jangmoo": {
    "tier": "LC"
  },
  "hakamoo": {
    "tier": "NFE"
  },
  "kommoo": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "kommoototem": {
    "tier": "Illegal"
  },
  "tapukoko": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "tapulele": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "tapubulu": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "tapufini": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "cosmog": {
    "tier": "LC"
  },
  "cosmoem": {
    "tier": "NFE"
  },
  "solgaleo": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "lunala": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "nihilego": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "buzzwole": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "pheromosa": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "xurkitree": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "celesteela": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "kartana": {
    "tier": "Illegal",
    "natDexTier": "UUBL"
  },
  "guzzlord": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "necrozma": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "necrozmaduskmane": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "necrozmadawnwings": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "necrozmaultra": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "magearna": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "magearnamega": {
    "tier": "Illegal"
  },
  "magearnaoriginalmega": {
    "tier": "Illegal"
  },
  "marshadow": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "poipole": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "naganadel": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "stakataka": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "blacephalon": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "zeraora": {
    "tier": "Illegal",
    "natDexTier": "UU"
  },
  "zeraoramega": {
    "tier": "Illegal"
  },
  "meltan": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "melmetal": {
    "tier": "Illegal",
    "natDexTier": "OU"
  },
  "melmetalgmax": {
    "tier": "Illegal"
  },
  "grookey": {
    "tier": "LC"
  },
  "thwackey": {
    "tier": "NUBL",
    "doublesTier": "NFE",
    "natDexTier": "NFE"
  },
  "rillaboom": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "rillaboomgmax": {
    "tier": "Illegal"
  },
  "scorbunny": {
    "tier": "LC"
  },
  "raboot": {
    "tier": "NFE"
  },
  "cinderace": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "cinderacegmax": {
    "tier": "Illegal"
  },
  "sobble": {
    "tier": "LC"
  },
  "drizzile": {
    "tier": "NFE"
  },
  "inteleon": {
    "tier": "PUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "inteleongmax": {
    "tier": "Illegal"
  },
  "skwovet": {
    "tier": "LC"
  },
  "greedent": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rookidee": {
    "tier": "LC"
  },
  "corvisquire": {
    "tier": "NFE"
  },
  "corviknight": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "corviknightgmax": {
    "tier": "Illegal"
  },
  "blipbug": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "dottler": {
    "tier": "Illegal",
    "natDexTier": "NFE"
  },
  "orbeetle": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "orbeetlegmax": {
    "tier": "Illegal"
  },
  "nickit": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "thievul": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "gossifleur": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "eldegoss": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "wooloo": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "dubwool": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "chewtle": {
    "tier": "LC"
  },
  "drednaw": {
    "tier": "PUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "drednawgmax": {
    "tier": "Illegal"
  },
  "yamper": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "boltund": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "rolycoly": {
    "tier": "LC"
  },
  "carkol": {
    "tier": "NFE"
  },
  "coalossal": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "coalossalgmax": {
    "tier": "Illegal"
  },
  "applin": {
    "tier": "LC"
  },
  "flapple": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "flapplegmax": {
    "tier": "Illegal"
  },
  "appletun": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "appletungmax": {
    "tier": "Illegal"
  },
  "dipplin": {
    "tier": "NFE"
  },
  "silicobra": {
    "tier": "LC"
  },
  "sandaconda": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sandacondagmax": {
    "tier": "Illegal"
  },
  "cramorant": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "arrokuda": {
    "tier": "LC"
  },
  "barraskewda": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "toxel": {
    "tier": "LC"
  },
  "toxtricity": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "toxtricitygmax": {
    "tier": "Illegal"
  },
  "toxtricitylowkeygmax": {
    "tier": "Illegal"
  },
  "sizzlipede": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "centiskorch": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "centiskorchgmax": {
    "tier": "Illegal"
  },
  "clobbopus": {
    "tier": "Illegal",
    "natDexTier": "LC"
  },
  "grapploct": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "sinistea": {
    "tier": "LC"
  },
  "polteageist": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "hatenna": {
    "tier": "LC"
  },
  "hattrem": {
    "tier": "NFE"
  },
  "hatterene": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "hatterenegmax": {
    "tier": "Illegal"
  },
  "impidimp": {
    "tier": "LC"
  },
  "morgrem": {
    "tier": "NFE"
  },
  "grimmsnarl": {
    "tier": "PU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "grimmsnarlgmax": {
    "tier": "Illegal"
  },
  "milcery": {
    "tier": "LC"
  },
  "alcremie": {
    "tier": "ZUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "alcremiegmax": {
    "tier": "Illegal"
  },
  "falinks": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "falinksmega": {
    "tier": "Illegal"
  },
  "pincurchin": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "snom": {
    "tier": "LC"
  },
  "frosmoth": {
    "tier": "PUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "stonjourner": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "eiscue": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "indeedee": {
    "tier": "PUBL",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "indeedeef": {
    "tier": "ZU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "morpeko": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "cufant": {
    "tier": "LC"
  },
  "copperajah": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "copperajahgmax": {
    "tier": "Illegal"
  },
  "dracozolt": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "arctozolt": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "dracovish": {
    "tier": "Illegal",
    "natDexTier": "Uber"
  },
  "arctovish": {
    "tier": "Illegal",
    "natDexTier": "RU"
  },
  "duraludon": {
    "tier": "NU",
    "doublesTier": "NFE",
    "natDexTier": "RU"
  },
  "duraludongmax": {
    "tier": "Illegal"
  },
  "dreepy": {
    "tier": "LC"
  },
  "drakloak": {
    "tier": "NFE"
  },
  "dragapult": {
    "tier": "OU",
    "doublesTier": "DUU",
    "natDexTier": "Uber"
  },
  "zacian": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "zaciancrowned": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "zamazenta": {
    "tier": "OU",
    "doublesTier": "DUber",
    "natDexTier": "OU"
  },
  "zamazentacrowned": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "eternatus": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "eternatuseternamax": {
    "tier": "Illegal"
  },
  "kubfu": {
    "tier": "NFE"
  },
  "urshifu": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "urshifurapidstrike": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "OU"
  },
  "urshifugmax": {
    "tier": "Illegal"
  },
  "urshifurapidstrikegmax": {
    "tier": "Illegal"
  },
  "zarude": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "regieleki": {
    "tier": "Uber",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "regidrago": {
    "tier": "NUBL",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "glastrier": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "spectrier": {
    "tier": "Uber",
    "doublesTier": "(DUU)",
    "natDexTier": "Uber"
  },
  "calyrex": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "calyrexice": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "calyrexshadow": {
    "tier": "AG",
    "doublesTier": "DUber",
    "natDexTier": "AG"
  },
  "enamorus": {
    "tier": "OU",
    "doublesTier": "DUU",
    "natDexTier": "RUBL"
  },
  "enamorustherian": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "sprigatito": {
    "tier": "LC"
  },
  "floragato": {
    "tier": "NFE"
  },
  "meowscarada": {
    "tier": "UUBL",
    "doublesTier": "DUU",
    "natDexTier": "UUBL"
  },
  "fuecoco": {
    "tier": "LC"
  },
  "crocalor": {
    "tier": "NFE"
  },
  "skeledirge": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "quaxly": {
    "tier": "LC"
  },
  "quaxwell": {
    "tier": "NFE"
  },
  "quaquaval": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "lechonk": {
    "tier": "LC"
  },
  "oinkologne": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "oinkolognef": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "tarountula": {
    "tier": "LC"
  },
  "spidops": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "nymble": {
    "tier": "LC"
  },
  "lokix": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "rellor": {
    "tier": "LC"
  },
  "rabsca": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "greavard": {
    "tier": "LC"
  },
  "houndstone": {
    "tier": "NU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "flittle": {
    "tier": "NFE"
  },
  "espathra": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "wiglett": {
    "tier": "LC"
  },
  "wugtrio": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "dondozo": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "veluza": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "finizen": {
    "tier": "LC"
  },
  "palafin": {
    "tier": "Uber",
    "doublesTier": "(DUU)",
    "natDexTier": "Uber"
  },
  "smoliv": {
    "tier": "LC"
  },
  "dolliv": {
    "tier": "NFE"
  },
  "arboliva": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "capsakid": {
    "tier": "LC"
  },
  "scovillain": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "scovillainmega": {
    "tier": "Illegal"
  },
  "tadbulb": {
    "tier": "LC"
  },
  "bellibolt": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "varoom": {
    "tier": "LC"
  },
  "revavroom": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "orthworm": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "tandemaus": {
    "tier": "LC"
  },
  "maushold": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "cetoddle": {
    "tier": "LC"
  },
  "cetitan": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "frigibax": {
    "tier": "LC"
  },
  "arctibax": {
    "tier": "NFE"
  },
  "baxcalibur": {
    "tier": "Uber",
    "doublesTier": "DUU",
    "natDexTier": "Uber"
  },
  "baxcaliburmega": {
    "tier": "Illegal"
  },
  "tatsugiri": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "tatsugiricurlymega": {
    "tier": "Illegal"
  },
  "tatsugiridroopymega": {
    "tier": "Illegal"
  },
  "tatsugiristretchymega": {
    "tier": "Illegal"
  },
  "cyclizar": {
    "tier": "RU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "pawmi": {
    "tier": "LC"
  },
  "pawmo": {
    "tier": "NFE"
  },
  "pawmot": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "wattrel": {
    "tier": "LC"
  },
  "kilowattrel": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "bombirdier": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "squawkabilly": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "flamigo": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "klawf": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "nacli": {
    "tier": "LC"
  },
  "naclstack": {
    "tier": "NFE"
  },
  "garganacl": {
    "tier": "OU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "glimmet": {
    "tier": "LC"
  },
  "glimmora": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "UU"
  },
  "glimmoramega": {
    "tier": "Illegal"
  },
  "shroodle": {
    "tier": "LC"
  },
  "grafaiai": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "fidough": {
    "tier": "LC"
  },
  "dachsbun": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "maschiff": {
    "tier": "LC"
  },
  "mabosstiff": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "bramblin": {
    "tier": "LC"
  },
  "brambleghast": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "gimmighoul": {
    "tier": "LC"
  },
  "gimmighoulroaming": {
    "tier": "LC"
  },
  "gholdengo": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "greattusk": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "brutebonnet": {
    "tier": "ZU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "sandyshocks": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "screamtail": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "fluttermane": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "slitherwing": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "roaringmoon": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "irontreads": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "ironmoth": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "ironhands": {
    "tier": "UUBL",
    "doublesTier": "DOU",
    "natDexTier": "UUBL"
  },
  "ironjugulis": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ironthorns": {
    "tier": "NUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ironbundle": {
    "tier": "Uber",
    "doublesTier": "DUU",
    "natDexTier": "Uber"
  },
  "ironvaliant": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "tinglu": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "chienpao": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "wochien": {
    "tier": "PU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "chiyu": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "koraidon": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "AG"
  },
  "miraidon": {
    "tier": "AG",
    "doublesTier": "DUber",
    "natDexTier": "AG"
  },
  "tinkatink": {
    "tier": "LC"
  },
  "tinkatuff": {
    "tier": "NFE"
  },
  "tinkaton": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "charcadet": {
    "tier": "LC"
  },
  "armarouge": {
    "tier": "RU",
    "doublesTier": "DUU",
    "natDexTier": "RU"
  },
  "ceruledge": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "toedscool": {
    "tier": "LC"
  },
  "toedscruel": {
    "tier": "ZU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "kingambit": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "clodsire": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "OU"
  },
  "annihilape": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "walkingwake": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "ironleaves": {
    "tier": "RUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "poltchageist": {
    "tier": "LC"
  },
  "sinistcha": {
    "tier": "UU",
    "doublesTier": "DOU",
    "natDexTier": "RU"
  },
  "okidogi": {
    "tier": "UUBL",
    "doublesTier": "DOU",
    "natDexTier": "UUBL"
  },
  "munkidori": {
    "tier": "NU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "fezandipiti": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ogerpon": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "RU"
  },
  "ogerponwellspring": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "ogerponhearthflame": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "ogerponcornerstone": {
    "tier": "UUBL",
    "doublesTier": "DUU",
    "natDexTier": "UUBL"
  },
  "archaludon": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "RUBL"
  },
  "hydrapple": {
    "tier": "UU",
    "doublesTier": "(DUU)",
    "natDexTier": "UU"
  },
  "gougingfire": {
    "tier": "Uber",
    "doublesTier": "DOU",
    "natDexTier": "Uber"
  },
  "ragingbolt": {
    "tier": "OU",
    "doublesTier": "DOU",
    "natDexTier": "OU"
  },
  "ironboulder": {
    "tier": "UUBL",
    "doublesTier": "(DUU)",
    "natDexTier": "RUBL"
  },
  "ironcrown": {
    "tier": "OU",
    "doublesTier": "DUU",
    "natDexTier": "UUBL"
  },
  "terapagos": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "OU"
  },
  "terapagosstellar": {
    "tier": "Uber",
    "doublesTier": "DUber",
    "natDexTier": "Uber"
  },
  "pecharunt": {
    "tier": "OU",
    "doublesTier": "(DUU)",
    "natDexTier": "UUBL"
  },
  "missingno": {
    "tier": "Illegal"
  },
  "syclar": {
    "tier": "CAP LC"
  },
  "syclant": {
    "tier": "CAP"
  },
  "revenankh": {
    "tier": "CAP"
  },
  "embirch": {
    "tier": "CAP LC"
  },
  "flarelm": {
    "tier": "CAP NFE"
  },
  "pyroak": {
    "tier": "CAP"
  },
  "breezi": {
    "tier": "CAP LC"
  },
  "fidgit": {
    "tier": "CAP"
  },
  "rebble": {
    "tier": "CAP LC"
  },
  "tactite": {
    "tier": "CAP NFE"
  },
  "stratagem": {
    "tier": "CAP"
  },
  "privatyke": {
    "tier": "CAP LC"
  },
  "arghonaut": {
    "tier": "CAP"
  },
  "nohface": {
    "tier": "CAP LC"
  },
  "kitsunoh": {
    "tier": "CAP"
  },
  "monohm": {
    "tier": "CAP LC"
  },
  "duohm": {
    "tier": "CAP NFE"
  },
  "cyclohm": {
    "tier": "CAP"
  },
  "dorsoil": {
    "tier": "CAP LC"
  },
  "colossoil": {
    "tier": "CAP"
  },
  "protowatt": {
    "tier": "CAP LC"
  },
  "krilowatt": {
    "tier": "CAP"
  },
  "voodoll": {
    "tier": "CAP LC"
  },
  "voodoom": {
    "tier": "CAP"
  },
  "scratchet": {
    "tier": "CAP LC"
  },
  "tomohawk": {
    "tier": "CAP"
  },
  "necturine": {
    "tier": "CAP LC"
  },
  "necturna": {
    "tier": "CAP"
  },
  "mollux": {
    "tier": "CAP"
  },
  "cupra": {
    "tier": "CAP LC"
  },
  "argalis": {
    "tier": "CAP NFE"
  },
  "aurumoth": {
    "tier": "CAP"
  },
  "brattler": {
    "tier": "CAP LC"
  },
  "malaconda": {
    "tier": "CAP"
  },
  "cawdet": {
    "tier": "CAP LC"
  },
  "cawmodore": {
    "tier": "CAP"
  },
  "volkritter": {
    "tier": "CAP LC"
  },
  "volkraken": {
    "tier": "CAP"
  },
  "snugglow": {
    "tier": "CAP LC"
  },
  "plasmanta": {
    "tier": "CAP"
  },
  "floatoy": {
    "tier": "CAP LC"
  },
  "caimanoe": {
    "tier": "CAP NFE"
  },
  "naviathan": {
    "tier": "CAP"
  },
  "crucibelle": {
    "tier": "CAP"
  },
  "crucibellemega": {
    "tier": "CAP"
  },
  "pluffle": {
    "tier": "CAP LC"
  },
  "kerfluffle": {
    "tier": "CAP"
  },
  "pajantom": {
    "tier": "CAP"
  },
  "mumbao": {
    "tier": "CAP LC"
  },
  "jumbao": {
    "tier": "CAP"
  },
  "fawnifer": {
    "tier": "CAP LC"
  },
  "electrelk": {
    "tier": "CAP NFE"
  },
  "caribolt": {
    "tier": "CAP"
  },
  "smogecko": {
    "tier": "CAP LC"
  },
  "smoguana": {
    "tier": "CAP NFE"
  },
  "smokomodo": {
    "tier": "CAP"
  },
  "swirlpool": {
    "tier": "CAP LC"
  },
  "coribalis": {
    "tier": "CAP NFE"
  },
  "snaelstrom": {
    "tier": "CAP"
  },
  "justyke": {
    "tier": "CAP LC"
  },
  "equilibra": {
    "tier": "CAP"
  },
  "solotl": {
    "tier": "CAP LC"
  },
  "astrolotl": {
    "tier": "CAP"
  },
  "miasmite": {
    "tier": "CAP LC"
  },
  "miasmaw": {
    "tier": "CAP"
  },
  "chromera": {
    "tier": "CAP"
  },
  "venomicon": {
    "tier": "CAP"
  },
  "venomiconepilogue": {
    "tier": "CAP"
  },
  "saharascal": {
    "tier": "CAP LC"
  },
  "saharaja": {
    "tier": "CAP"
  },
  "ababo": {
    "tier": "CAP LC"
  },
  "scattervein": {
    "tier": "CAP NFE"
  },
  "hemogoblin": {
    "tier": "CAP"
  },
  "cresceidon": {
    "tier": "CAP"
  },
  "chuggon": {
    "tier": "CAP LC"
  },
  "draggalong": {
    "tier": "CAP NFE"
  },
  "chuggalong": {
    "tier": "CAP"
  },
  "flox": {
    "tier": "CAP LC"
  },
  "shox": {
    "tier": "CAP"
  },
  "ramnarok": {
    "tier": "CAP"
  },
  "ramnarokradiant": {
    "tier": "Illegal"
  },
  "pokestarsmeargle": {
    "tier": "Illegal"
  },
  "pokestarufo": {
    "tier": "Illegal"
  },
  "pokestarufo2": {
    "tier": "Illegal"
  },
  "pokestarbrycenman": {
    "tier": "Illegal"
  },
  "pokestarmt": {
    "tier": "Illegal"
  },
  "pokestarmt2": {
    "tier": "Illegal"
  },
  "pokestartransport": {
    "tier": "Illegal"
  },
  "pokestargiant": {
    "tier": "Illegal"
  },
  "pokestarhumanoid": {
    "tier": "Illegal"
  },
  "pokestarmonster": {
    "tier": "Illegal"
  },
  "pokestarf00": {
    "tier": "Illegal"
  },
  "pokestarf002": {
    "tier": "Illegal"
  },
  "pokestarspirit": {
    "tier": "Illegal"
  },
  "pokestarblackdoor": {
    "tier": "Illegal"
  },
  "pokestarwhitedoor": {
    "tier": "Illegal"
  },
  "pokestarblackbelt": {
    "tier": "Illegal"
  },
  "pokestarufopropu2": {
    "tier": "Illegal"
  }
} as const
