import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const SOURCE_URL =
  'https://raw.githubusercontent.com/smogon/pokemon-showdown/master/data/formats-data.ts'
const OUTPUT_PATH = path.resolve('src/lib/tier-data.ts')

const SHOWDOWN_ID_RE = /^[\t ]([a-z0-9]+): \{\n([\s\S]*?)\n\t\}/gm

const parseValue = (body: string, key: string) => {
  const match = body.match(new RegExp(`${key}: "([^"]+)"`))
  return match?.[1] ?? null
}

const main = async () => {
  const response = await fetch(SOURCE_URL)
  if (!response.ok) {
    throw new Error(`Failed to fetch tier data: ${response.status}`)
  }

  const source = await response.text()
  const rows: Record<string, { tier?: string; doublesTier?: string; natDexTier?: string }> = {}
  for (const match of source.matchAll(SHOWDOWN_ID_RE)) {
    const id = match[1]
    const body = match[2]
    const tier = parseValue(body, 'tier')
    const doublesTier = parseValue(body, 'doublesTier')
    const natDexTier = parseValue(body, 'natDexTier')
    if (tier || doublesTier || natDexTier) {
      rows[id] = {
        ...(tier ? { tier } : {}),
        ...(doublesTier ? { doublesTier } : {}),
        ...(natDexTier ? { natDexTier } : {}),
      }
    }
  }

  await mkdir(path.dirname(OUTPUT_PATH), { recursive: true })
  await writeFile(
    OUTPUT_PATH,
    [
      '// Generated by scripts/generate-tiers.ts from Pokemon Showdown formats data.',
      'export type TierInfo = { tier?: string; doublesTier?: string; natDexTier?: string }',
      `export const TIER_DATA: Record<string, TierInfo> = ${JSON.stringify(rows, null, 2)} as const`,
      '',
    ].join('\n'),
    'utf8',
  )

  console.log(`Generated ${Object.keys(rows).length} tier rows at ${OUTPUT_PATH}`)
}

void main()
